## AGH University
## Python in Electrical Engineering - Autumn 2022
## Lab 1 - Python 3 programming excercises


In [ ]:
import piplite
await piplite.install(['numpy', 'matplotlib', 'scipy', 'bitstring'])

### <font color='blue'>PART 1</font>
### <font color='blue'>PEP 8 -- Style Guide for Python Code</font>

https://www.python.org/dev/peps/pep-0008/

#### 1.1 Reformat the following code to be aligned with PEP 8 - Naming variables and constants

In [10]:
# There are four variables that hold the EUR prices of the following products: eggs, potatoes, mushrooms and meat:
eggs = 45
potatoes = 12
mushrooms = 9
meat = 30

# and one constant that stores the discount level:
discount = 87 # constant percentage value

# Then the total price (including discount) is calculated and printed out:
x = (eggs + potatoes + mushrooms + meat) * discount/100
print(f'The total price after discount is EUR {x}')

The total price after discount is EUR 83.52


#### 1.2 Reformat the following code to be aligned with PEP 8 - Naming functions

In [9]:
# There is a declaration of function that checks if a given number is prime:
def liczbypierwsze(number):
    flag = False
    if number > 1:
        for i in range(2, number):
            if (number % i) == 0:
                flag = True
                break
    if flag:
        print(number, "is not a prime number")
    else:
        print(number, "is a prime number")

# Example function call
liczbypierwsze(51)

51 is not a prime number


#### 1.3 Reformat the following code to work and to be aligned with PEP 8 - Indentation, comments, whitespaces around assignment operators and comparisons

In [20]:
import numpy as np

random_list=np.random.randint(100, size = (10, 10))          # This is a 10x10 list of random numbers Find the location (row,column)
                                                             # and the value of its maximum element  

value_max = 0         #Inicjalization of variable which will store the maximum value
i_max = 0
j_max = 0             #ThisVariableStoresJIndex
for i in range(0,len(random_list)):
    for j in range(0,len(random_list)):
        if random_list[i,j] > value_max:
            value_max = random_list[i,j]
            i_max = i
            j_max = j
print(f'List of random elements: \n {random_list}')            
print(f'Maximum element {value_max} is located at {i_max},{j_max}')  

List of random elements: 

 [[22 29 86 67 45 93 27 61 66 10]

 [56 78 39 35 79  7 61  7 87 24]

 [ 5 13 94 60 64 43 74 51 55 67]

 [96 27 63 88 17 12 84 33 30 59]

 [ 6 94 36 50 45 13 69 92 35 92]

 [13 44 50 67 92 41 38 90 56 37]

 [74 82  9 29 18 41 34 88 53 20]

 [54  7 66 65 42 53 33 43 77 30]

 [74 11  9  2 68 51 87 51 88 25]

 [79 79  6  0 94 29 42 55 93 38]]

Maximum element 96 is located at 3,0


### <font color='blue'>PART 2</font>
### <font color='blue'>Built-in variables in Python</font>

#### 2.1 Create program to reverse words in a given string

In [10]:
text = 'hey hi hello' #input("Enter text: ")
words = text.split()
x = len(words)
words.reverse()
words[::-1]
print(words)
#i=0
#while i < len(words):
 #   print(words[i])
  #  i += 1

#zdanie    
# Write your code here:
#  this program compiling correctly in Pycharm, the jupyter lab has problems due to compilation of reading type of inputed text by user
# text = input("Enter text: ")
# print(" ".join(text.split()[::-1]))


['hello', 'hi', 'hey']


#### 2.2 Create program that returns a tuple with repeated elements in a given list

In [ ]:
# Write your code here:
def convert(list):
    return tuple(list)
  
# Driver function
list = [3, 3, 3, 4]
print(convert(list))

#### 2.3 Compare the size and the processing speed between Python lists, Python tuples and Numpy nd.arrays  for different dataset_size (from 1 to 10e7) and two mathematical operations: 
- adding scalar
- dot product

In [26]:
import numpy as np
import random
import sys
import time

########################################
# Creating [1xdata_set] variables with exactly the same content (int numbers)

dataset_size = 1000 # Value to be modified
my_list = []
for i in range(0,dataset_size):
    random_number = random.randint(0,100)
    my_list.append(random_number)

my_tuple = tuple(my_list)
my_ndarray = np.array(my_list)
print(type(my_list), sys.getsizeof(my_list),"bytes")
print(type(my_tuple), sys.getsizeof(my_tuple),"bytes")
print(type(my_ndarray), sys.getsizeof(my_ndarray),"bytes")
print()
########################################


########################################
# Adding scalar
print("Adding scalar:")

scalar = 123
start = time.process_time()
for i in range(0,len(my_list)):
    my_list[i] += scalar
end = time.process_time()
print("list:",round((end - start) * 1000,6), "ms")


scalar = 123
start = time.process_time()
my_ndarray += scalar
end = time.process_time()
print("nd.array:" ,round((end - start) * 1000,6), "ms")
print()
########################################


########################################
# Dot product of two wectors. This is one of the most important calculations in machine learning.
print("Dot product:")

sum = 0
start = time.process_time()
for i in range(0,len(my_list)):
    sum += my_list[i] * my_list[i]
end = time.process_time()
print("list:",round((end - start) * 1000,6), "ms")

sum = 0
start = time.process_time()
for i in range(0,len(my_tuple)):
    sum += my_tuple[i] * my_tuple[i]
end = time.process_time()
print("tuple:",round((end - start) * 1000,6), "ms")

sum = 0
start = time.process_time()
np.dot(my_ndarray,my_ndarray)
end = time.process_time()
print("nd.array:",round((end - start) * 1000,6), "ms")
########################################



# Decribe your results here. Explain noticed time differences.
#this part of exercises is done in pycharm
# For dataset_size 10e7 class list has the most bytes than the others and it is 89095160 bytes, for class tuple it is 80000040 bytes and numpy is 40000112. For adding scalar method time to compile list is:1218.75ms for nd.array 0.0 ms. For Dot pruduct method time to compile list is 1515.625 ms, tuple 1609.375ms and nd.array 0.0ms.
# For dataset_size from 1 to 10e4 the results are the same and it is any difference between them.
# For dataset_size 10e5 class list has the most bytes than the others and it is 800984 bytes, for class tuple it is 800040 bytes and numpy is 400112 bytes. For adding scalar method time to compile list is:15.625ms for nd.array 0.0 ms. For Dot pruduct method time to compile list is 15.625 ms, tuple 31.25ms and nd.array 0.0ms.
# For dataset_size 10e6 class list has the most bytes than the others and it is 8448728 bytes bytes, for class tuple it is 8000040 bytes and numpy is 4000112 bytes. For adding scalar method time to compile list is:109.375 ms for nd.array 0.0 ms. For Dot pruduct method time to compile list is 171.875 ms, tuple 171.875 ms and nd.array 0.0ms.
# Summary
# which inreasing the dataset_size the times for specific classes increasing too, class numpy have already the lowest size, the most dynamic method to compile is list because have the lowest time needed to compile 

<class 'list'> 4428 bytes

<class 'tuple'> 4020 bytes

<class 'numpy.ndarray'> 4056 bytes



Adding scalar:

list: 0.0 ms

nd.array: 0.0 ms



Dot product:

list: 0.0 ms

tuple: 0.0 ms

nd.array: 0.0 ms


#### 2.4 Create a dictionary where keys are the unique values of a given list and values are their frequencies in a given list

In [ ]:
# Write your code here:
from collections import defaultdict
def frequencies(lst):
  freq = defaultdict(int)
  for val in lst:
    freq[val] += 1
  return dict(freq) 
print(frequencies(['a', 'b', 'f', 'a', 'c', 'e', 'a', 'a', 'b', 'e', 'f'])) 
print(frequencies([3,4,7,5,9,3,4,5,0,3,2,3])

#### 2.5 Estimate and compare the Big O notation for a membership test in lists, tuples, ndarrays and sets
https://www.freecodecamp.org/news/big-o-notation-why-it-matters-and-why-it-doesnt-1674cfa8a23c/

In [1]:
import numpy as np
import random
import sys
import time

########################################
# Creating [1xdata_set] variables with exactly the same content (float numbers)

dataset_size = 10000000
my_list = []
for i in range(0,dataset_size):
    random_number = random.uniform(0,100)
    my_list.append(random_number)

my_tuple = tuple(my_list)
my_ndarray = np.array(my_list)
my_set = set(my_list)

print(type(my_list), sys.getsizeof(my_list),"bytes")
print(type(my_tuple), sys.getsizeof(my_tuple),"bytes")
print(type(my_ndarray), sys.getsizeof(my_ndarray),"bytes")
print(type(my_set), sys.getsizeof(my_set),"bytes")
print()
########################################

########################################
# Example of the membership test in a list
start = time.process_time()
1 in my_list
end = time.process_time()
print("Membership test time of a list:",round((end - start) * 1000,6), "ms")


# Example of the membership test in a list
start = time.process_time()
1 in my_ndarray
end = time.process_time()
print("Membership test time of a ndarray:",round((end - start) * 1000,6), "ms")


# Example of the membership test in a set
start = time.process_time()
1 in my_set
end = time.process_time()
print("Membership test time of a set:",round((end - start) * 1000,6), "ms")

# Write your code, results and comments here. Explain noticed BigO differences. 
# You can use matplotlib library for results visualisation
#For dataset_size 10e7 classes have : list( 89095160 bytes), tuple(80000040 bytes), numpy.ndarray(80000112 bytes), set(268435672 bytes) and membership test times are : Membership test time of a list: 203.125 ms,Membership test time of a ndarray: 31.25 ms, Membership test time of a set: 0.0 ms
#For dataset_size 10e6 classes have : list( 8448728 bytes), tuple(8000040 bytes), numpy.ndarray(8000112 bytes), set(33554648 bytes) and membership test times are : Membership test time of a list: 15.625 ms,Membership test time of a ndarray: 15.625 ms, Membership test time of a set: 0.0 ms
#For dataset_size 10e5 classes have : list( 800984 bytes), tuple(800040 bytes), numpy.ndarray(800112 bytes), set(4194520 bytes) and membership test times are : Membership test time of a list: 0.0ms,Membership test time of a ndarray: 0.0 ms, Membership test time of a set: 0.0 ms
# Summary
# Generally class set have the most bytes, below dataset_size 10e5 membership test time is not relevant for any class because all are 0, for dataset_size above 10e5 membership test for class ndarray is the fastest 


<class 'list'> 44547580 bytes

<class 'tuple'> 40000020 bytes

<class 'numpy.ndarray'> 80000056 bytes

<class 'set'> 134217836 bytes



Membership test time of a list: 0.0 ms

Membership test time of a ndarray: 0.0 ms

Membership test time of a set: 0.0 ms


### <font color='blue'>PART 3</font>
### <font color='blue'>Conditionals and loops</font>

##### 3.1 Calculate the value of the expression:


$$\sum^{10}_{\begin{gathered}i=1\\ k=1\\ i\neq k\end{gathered} } i\cdot k=$$

In [22]:
i=1
k=1
x=0
while i <= 10:
    x = (i * k) + x
    i += 1
print(x)

55


##### 3.2 Calculate the value of the expression:


$$\sqrt[3]{\sum^{10}_{i=1} \prod^{i}_{j=1} cos(\pi \cdot i)}= $$

In [34]:
# Write your code here:
from math import pi
from math import cos
suma = 0
Sum = 0
a=1
for i in range(1,11):
    a = cos(i*pi)*a
    Sum += a
print(Sum)
test = Sum * -1
wynik = test ** (1/3)
koniec = wynik * -1
print (koniec)


-2.0
-1.2599210498948732


##### 3.3 Calculate the value of the expression:


x= [92, 82, 64, 39, 82, 72, 39, 100, 58, 28, 100, 50, 8, 51, 56, 49, 85, 99, 88, 41]

$$\sqrt{\frac{1}{n} \sum^{11}_{0} x[i]}= $$

In [38]:
# Write your code here:
from math import sqrt
x = [92, 82, 64, 39, 82, 72, 39, 100, 58, 28, 100, 50, 8, 51, 56, 49, 85, 99, 88, 41]
i = 0
n = len(x)
suma = 0
while i <= 11:
    suma = x[i] + suma
    i += 1
wynik = suma / n
sqrt(wynik)


6.348228099241551


##### 3.4 Create a program to check the validity of the entered password

- Allowed length: from 8 do 16 characters,
- At least 1 letter between [a-z], 
- At least 1 letter between [A-Z],
- At least 1 number between [0,9]
- At least 1 character from [!@#].



In [7]:
pswd = ("Elooooo1!")
literki = list(range(97, 123))
litery = list(range(65, 91))
cyferki = list(range(48, 58))
znaki = [33, 35, 64]


def zamiana(x):
    l = len(x)
    i = 0
    while i < l:
        x[i] = chr(x[i])
        i += 1
    return x

def sprawdzanie(x, y):
    dlugosc = len(y)
    n = 0
    while n < dlugosc:
        if (y[n] in x) == True:
            return "OK"
        elif (y[n] in x) == False:
            n += 1
            if n == dlugosc:
                return "Brak"


dlugosc = len(pswd)
if dlugosc < 8:
    print("Hasło jest za krótkie !")
elif dlugosc > 16:
    print("Hasło jest za długie !")
else:
    m = zamiana(literki)
    M = zamiana(litery)
    Z = zamiana(znaki)
    C = zamiana(cyferki)

    h = sprawdzanie(pswd, m)
    i = sprawdzanie(pswd, M)
    j = sprawdzanie(pswd, Z)
    k = sprawdzanie(pswd, C)
    print('Małe literki: ', h)
    print('Duże litery: ', i)
    print('Znaki specjalne: ', j)
    print('Cyfry: ', k)

Małe literki:  OK

Duże litery:  OK

Znaki specjalne:  OK

Cyfry:  OK


##### 3.5 Generate an array [1x32] filled with randomly placed zeros and ones. Then write an algorithm that converts this array to a decimal number using the IEEE 754 standard defining a binary 32-bit floating point number.

https://en.wikipedia.org/wiki/IEEE_754

https://en.wikibooks.org/wiki/A-level_Computing/AQA/Paper_2/Fundamentals_of_data_representation/Floating_point_numbers

#### Example 1:

Input array:
 [0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 

Exponent:
- Binary:  [1. 0. 0. 0. 0. 0. 0. 1.]

- Decimal:  129.0 

Mantissa:
- Binary: [1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

- Decimal:  0.75 

Result (decimal number):  7.0 

#### Example 2:

Input array:
 [1. 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 0. 0. 1. 1. 1. 1. 1. 1.] 

Exponent:  
- Binary: [1. 0. 0. 1. 1. 0. 0. 1.]

- Decimal:  153.0 

Mantissa:  
- Binary: [1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 1.]

- Decimal:  0.8280409574508667 

Result (decimal number):  -122677752.0 

In [32]:
# Write your code here:
from random import randint

i = 0
liczba = list(range(0,32))
#print(liczba)
while i < 32:
    liczba[i] = randint(0,1)
    i += 1
print(liczba)
n = 0
x = list(range(0,32))
suma = 0
while n < 32:
    if liczba[n] == 1:
        x[n] = 2**(31-n)
    elif liczba[n] == 0:
        x[n] = 0
    suma = suma + x[n]
    n += 1
#print(liczba[0],liczba[1])
#binarna = int(liczba)
#print(binarna)

print(suma)

"""Hint: You can use the bitstring function to verify the correctness of your algorithm."""
# import bitstring
# f1 = bitstring.BitArray(float=wynik, length=32)
# print(f1.bin)

[1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0]

3755783956


'Hint: You can use the bitstring function to verify the correctness of your algorithm.'

### <font color='blue'>PART 4</font>
### <font color='blue'>User functions</font>

##### 4.1 Create a function that determines the square root of a positive number using the Babylonian method with a given accuracy:

$$x_{0}\approx \sqrt{S} $$

$$x_{n+1}=\frac{1}{2} (x_{n}+\frac{S}{x_{n}} )$$

$$\sqrt{S} =\lim_{n\rightarrow \infty } x_{n}$$

In [36]:
def square_root(S, epsilon): #Two args: the positive number (S) and the accuracy (epsilon) 

    x = S**-2
    y = S/x
    while(x - y > epsilon):
        x = (1/2) * (x+y)
        y = S/x
        
    return x
     
print(square_root(15,0.001))
        

0.0044444444444444444


##### 4.2 Create a function that check if a given string contains every alphabet letter at least once

In [1]:
def sprawdzanie(x):
    dlugosc = len(x)
    literki = list(range(97,123))
    #litery = list(range(65,91))
    alfabet = literki# + litery
# zamiana
    l = len(alfabet)
    i = 0
    while i < l:
        alfabet[i] = chr(alfabet[i])
        i += 1
    n = 0
    while n < dlugosc:
        if (alfabet[n] in x) == True:
            n += 1
            if n == dlugosc:
                print('Ciąg posiada conajmniej jedną litere z alfabetu')
        elif (alfabet[n] in x) == False:
            print('Brak litery ', alfabet[n], ' w ciągu')
            break

wyraz = ['a','b','c','d','e','f','g','h','i','j','k','l','n','o','p','m','q','r','s','t','u','v','w','x','y','z']
#print(wyraz)
sprawdzanie(wyraz)

Brak litery  e  w ciągu
